### ISSUE TITLE
bug: signing failed with imported keystore

### ISSUE THREAD

**Issue by kitadai31** [kitadai31/revanced-manager-android5-7#12]
### Bug description

The new patcher fails if a keystore is imported. The old android6-7 one worked with an imported keystore. The new android5-7 one does work but only if I don't import a keystore.
(Quoted from https://t.me/rvx_for_a6_7_chat/3545)

### Version of ReVanced Manager and version & name of application you tried to patch

v1.17.1

### Installation type

None

### Device logs

```shell
.
```

### Patcher logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: SM-A510F
Android version: 7.0
Supported architectures: armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v17.34.36
Patches version: v2.160.7
Patches: client-spoof, custom-branding-icon-afn-red, custom-branding-name, custom-seekbar-color, custom-video-speed, default-video-quality, default-video-speed, disable-haptic-feedback, enable-external-browser, enable-minimized-playback, enable-old-quality-layout, enable-open-links-directly, enable-seekbar-tapping, enable-tablet-miniplayer, enable-wide-searchbar, force-vp9-codec, header-switch, hide-auto-captions, hide-auto-player-popup-panels, hide-autoplay-button, hide-button-container, hide-cast-button, hide-channel-watermark, hide-comment-component, hide-create-button, hide-crowdfunding-box, hide-email-address, hide-endscreen-cards, hide-endscreen-overlay, hide-filmstrip-overlay, hide-firsttime-background-notification, hide-flyout-panel, hide-fullscreen-panels, hide-general-ads, hide-info-cards, hide-live-chat-button, hide-mix-playlists, hide-next-prev-button, hide-player-captions-button, hide-player-overlay-filter, hide-shorts-button, hide-shorts-component, hide-snackbar, hide-startup-shorts-player, hide-stories, hide-suggested-actions, hide-time-and-seekbar, hide-tooltip-content, hide-video-ads, layout-switch, microg-support, optimize-resource, overlay-buttons, patch-options [Application Name of YouTube: ReVanced Extended, Package Name of YouTube: app.rvx.android.youtube, Custom Speed Values: 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 3.0, 5.0, Overlay button icon selection: new, Background color for the dark theme: @android:color/black], remove-player-button-background, return-youtube-dislike, sponsorblock, spoof-app-version, spoof-player-parameters, swipe-controls, switch-create-notification, theme, translations

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: kitadai31/revanced-patches-android6-7
Integration source: kitadai31/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
client-spoof succeeded
custom-branding-icon-afn-red succeeded
custom-branding-name succeeded
custom-seekbar-color succeeded
custom-video-speed succeeded
default-video-quality succeeded
default-video-speed succeeded
disable-haptic-feedback succeeded
enable-external-browser succeeded
enable-minimized-playback succeeded
enable-old-quality-layout succeeded
enable-open-links-directly succeeded
enable-seekbar-tapping succeeded
enable-tablet-miniplayer succeeded
enable-wide-searchbar succeeded
force-vp9-codec succeeded
header-switch succeeded
hide-auto-captions succeeded
hide-auto-player-popup-panels succeeded
hide-autoplay-button succeeded
hide-button-container succeeded
hide-cast-button succeeded
hide-channel-watermark succeeded
hide-comment-component succeeded
hide-create-button succeeded
hide-crowdfunding-box succeeded
hide-email-address succeeded
hide-endscreen-cards succeeded
hide-endscreen-overlay succeeded
hide-filmstrip-overlay succeeded
hide-firsttime-background-notification succeeded
hide-flyout-panel succeeded
hide-fullscreen-panels succeeded
hide-general-ads succeeded
hide-info-cards succeeded
hide-live-chat-button succeeded
hide-mix-playlists succeeded
hide-next-prev-button succeeded
hide-player-captions-button succeeded
hide-player-overlay-filter succeeded
hide-shorts-button succeeded
hide-shorts-component succeeded
hide-snackbar succeeded
hide-startup-shorts-player succeeded
hide-stories succeeded
hide-suggested-actions succeeded
hide-time-and-seekbar succeeded
hide-tooltip-content succeeded
hide-video-ads succeeded
layout-switch succeeded
microg-support succeeded
optimize-resource succeeded
overlay-buttons succeeded
patch-options succeeded
remove-player-button-background succeeded
return-youtube-dislike succeeded
sponsorblock succeeded
spoof-app-version succeeded
spoof-player-parameters succeeded
swipe-controls succeeded
switch-create-notification succeeded
theme succeeded
translations succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
An error occurred:
java.io.FileNotFoundException: /data/user/0/app.kitadai31.manager.flutter/cache/patcher/tmp-NDZIJB/patched.apk: open failed: ENOENT (No such file or directory)
 at libcore.io.IoBridge.open(IoBridge.java:455)
 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
 at com.android.apksig.ApkSigner.sign(SourceFile:0)
 at app.revanced.manager.flutter.utils.signing.Signer.signApk(SourceFile)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$33(SourceFile)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$S_uZlejwCCJ2DlEIsq6PpeMbHBY(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:762)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
 at libcore.io.Posix.open(Native Method)
 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
 at libcore.io.IoBridge.open(IoBridge.java:441)
 ... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The issue is solely related to the ReVanced Manager

**Comment by kitadai31** [comment]
I think it is resolved in v1.23.3
